repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.2
    hooks:
    - id: validate_manifest
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt check
        description: Check formatting with cargo fmt.
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--", "--check"]
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: rust
        pass_filenames: false
        args: []
      - id: cargo-clippy
        name: cargo clippy
        description: Run the Clippy linter on the package.
        entry: cargo clippy
        language: rust
        pass_filenames: false
        # args: ["--", "-D", "warnings"]
      - id: test
        name: cargo test
        description: Run tests with cargo test.
        entry: cargo test --
        language: rust
        types: [rust]
        stages: [push]
        args: []
