---
keys:
  - &scotte age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y

creation_rules:
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
          - *scotte
  - path_regex: .*\.sops\.env
    key_groups:
      - age:
          - *scotte
